K2InformaticsGmbH/dderl

priv/login.html
priv/static/styles/dderl.css

Moved the logout button from the dropdown to top right hand side

---

priv/static/scripts/dderl.table.js
src/dderl_resource.erl
src/oci_adapter.erl

cc @acautin 
@tgdriph3:
Switch branch with `git checkout export_csv_with_bind` (perhaps followed by `git pull`to be safe) in deps/dderl to continue your work and bug fixing and push (without touching master).
When implementation is completed and tested we will merge this pull request and into master and remove this branch.
Fixes #140

Fix support for "export_csv" with bind for OCI

---

src/dderl_session.erl

Fixes #144
Also fixed a small bug in erlimem https://github.com/K2InformaticsGmbH/erlimem/commit/0bfcad01308c0d0bd307168c689e450cd9f50747

RPC node not reachable error issue 

---

src/dderl_fsm.erl

Here are two screen shots - first rows & memory:
and - second memory & rows:

The combined column in histograms is now decomposed.

---

.gitignore

Removing idea specific entries.

Clean up gitignore.

---

priv/static/scripts/dderl.table.js

If there exists no view "`All Views`", dderl shows the following error message after connecting to the database: "Error: Unable to process the request".

Prevent deleting / renaming view "All Views"

---

priv/static/scripts/dderl.statsTable.js
priv/static/scripts/dderl.table.js

i.e. showing the number of selected rows in a histogram.

Showing the number of unique items in the top left cell.

---

priv/static/scripts/dderl.statsTable.js

At the first and at every new column sort.

The histogram window shows always the first row on top

---

src/dderl_fsm.erl

1. count descending
2. histogram columns (in order of selection) ascending

Histogram default sort

---

priv/static/scripts/login.js

Added error text to the login window in red
Fixes #145

Login error window

---

priv/static/scripts/dderl.sql.js
priv/static/scripts/dderl.table.js

Rename tables and sql windows even if they are not views 

---

priv/login.html
priv/static/scripts/dderl.js
priv/static/scripts/dderl.sql.js
priv/static/scripts/dderl.table.js
src/dderl_dal.erl
src/gen_adapter.erl
src/imem_adapter.erl
src/oci_adapter.erl

DDerl views represent (offloaded) database views which consist of
- a view definition consisting of a select query with
- - -  expression list and optional aliases (like DB views)
- - -  optional join conditions (like DB views)
- - - where clause and order by (like DB views) 
- additional presentation information (window size and position, column widths)
- DDerl Views serve as building blocks for Dashboards (layout of Dderl Views on a screen).

Replacing term View by term ddView.

---

priv/static/scripts/dderl.js
priv/static/scripts/dderl.sql.js
priv/static/scripts/dderl.table.js

View name by default when renaming and enter to submit 

---

start.sh

Fixed issue with starting dderl in a file path with spaces 

---

priv/static/scripts/dderl.termEditor.js
src/dderl_session.erl

Double escaping issues with \\n and \\t

---

priv/static/styles/slick.grid.css

Column resize handler width incresed to 15px 

---

priv/static/scripts/dderl.table.js
src/gen_adapter.erl

Not formatting json on the server 

---

priv/bower.json
priv/bower_components/jquery-dialogextend/.bower.json
priv/bower_components/jquery-dialogextend/jquery.dialogextend.js
priv/static/scripts/dderl.table.js
priv/static/styles/dderl.css

Using jQuery DialogExtend Plugin added function minimize
Fixes #222

Improved dialog 

---

priv/static/scripts/dderl.table.js
priv/static/styles/dderl.css

Change color of dialog icons
Effect on toolbar icons on dderl table
Fixes #230

Cosmetic changes

---

src/dderl_fsm.erl

Waiting only 1 minute.

---

src/dderl_fsm.erl

Only considering numeric values.

Adding minimum and maximum to statistics (#250)

---

priv/static/scripts/dderl.statsTable.js

Adding tooltips to the statistics window.

---

src/imem_adapter.erl

Restore as error dispay 

---

src/dderl_session.erl

fetching the host address from the tns with a catch

---

priv/static/index.js
priv/static/scripts/connect.js
priv/static/scripts/dderl.js
priv/static/scripts/dderl.table.js
priv/static/scripts/login.js
src/dderl.hrl
src/dderl_resource.erl
src/dderl_session.erl
src/dderl_session_sup.erl

implemented session using cookie
HTTP Only cookie of #281 
Fixes #296

Session as Cookie

---

priv/static/scripts/connect.js
priv/static/scripts/dderl.js
priv/static/scripts/login.js
src/dderl_session.erl
src/imem_adapter.erl

Password strength validation on server before changing 

---

priv/static/index.html
priv/static/scripts/screensaver.js
priv/static/styles/dderl.css

Black backround for canvas and elements without id

---

src/gen_adapter.erl

Fixes #312
```sql
select ckey, cvalue:listTest, :listParam from ddCache@
```

Parameter detection regexp improvement

---

RELEASE-DDERL.md
priv/README.md
priv/d3_examples/x-y12-chart-autoscale.js
priv/package.json
priv/static/scripts/dderl.js
rebar.config
rel/reltool.config
src/dderl.app.src
start.bat

* Spelling.
* Changes in the sh script should also be reflected in the bat scipt.
* add international time format
* Using https protocol instead of git for npm jquery-ui dependency to allow npm install from inside firewalls.
* Release 1.6.5

Sync with remote master (#1)

---

priv/static/scripts/login.js
src/dderl_session.erl

Logging in after screensaver - erlimem session timeout

---

priv/static/scripts/dderl.table.js
src/dderl_fsm.erl
src/dderl_session.erl
src/gen_adapter.erl

There seem to be some problems with unnecessary trailing space characters.

Renaming menu point Histogram to Distinct Count.

---

src/gen_adapter.erl

Fallback regexp fix

---

priv/static/scripts/dderl.js
priv/static/slickgrid/plugins/slick.cellexternalcopymanager.js

Cells with newlines and double quotes
Copy-Paste from DDerl to Excel (previously broken)
Google-SpreadSheet
Copy-Paste within DDErl (compatibility)
Clipboard encoding is different

CTRL+C/V dderl<->dderl/excel

---

src/dderl_session.erl
src/gen_adapter.erl
src/imem_adapter.erl
src/oci_adapter.erl

[CSVTest.csv](https://github.com/K2InformaticsGmbH/dderl/files/711125/CSVTest.csv.txt)

new line and " support in csv cell

---

priv/static/scripts/login.js

try catch added when accessesing window object of opener 

---

src/dderloci.erl
src/oci_adapter.erl

Closing port implementation change in oci_port support 

---

priv/dev/static/scripts/connect.js
priv/dev/static/styles/dderl.css

Connections sorting order and overflow

---

priv/dev/.jshintrc
priv/dev/package.json
priv/dev/static/dashboard/DashboardMenu.js
priv/dev/static/index.js
priv/dev/static/jquery-ui-helper/helper.js
priv/dev/static/scripts/connect.js
priv/dev/static/scripts/dderl.combobox.js
priv/dev/static/scripts/dderl.sql.js
priv/dev/static/scripts/dderl.statsTable.js
priv/dev/static/scripts/dderl.table.js
priv/dev/static/scripts/dderl.termEditor.js
priv/dev/static/scripts/login.js
priv/dev/static/slickgrid/lib/jquery.event.drag.js
priv/dev/static/slickgrid/slick.grid.js
priv/dev/static/styles/dderl.css
priv/dev/static/styles/jquery-ui-smoothness/jquery-ui.css
priv/dev/webpack.config.js

Fixes #414 
Updated webpack, jquery, jquery-ui and d3, tested with latest stable nodejs 6.10.2 and npm 3.10.10
To test:
Download nodejs 6.10.2 from https://nodejs.org/en/ it includes npm 3.10.10, verify the version using: ```
$ node -v
v6.10.2
$ npm -v
3.10.10
```
delete ``node_modules`` directory from dderl/priv/dev and run:
```
npm install
npm run build
```
Verify dderl looks the same as before (Working hard for it to be the case 😄 )

Updated front end libs

---

src/dderl.erl

dderl probe implementation

---

src/dderl_resource.erl
src/dderl_saml_handler.erl

Saml authentication failiure fix

---

src/dderl_access_logger.erl

access log not masking password while chaning password

---

src/dderl_access_logger.erl
src/dderl_session.erl

Password masked in alter user identified query

---

src/dderl_fsm.erl

Migrated gen_fsm to gen_statem 

---

src/dderl_dal.erl
src/imem_adapter.erl

TCP connect not converting binary schema to atom

---

priv/dev/static/scripts/connect.js
src/dderl_dal.erl
src/dderl_session.erl
src/imem_adapter.erl

related to https://github.com/K2InformaticsGmbH/erlimem/issues/25

removed rpc interface

---

priv/dev/static/scripts/dderl.sql.js

ctrl + enter to execute query 

---

priv/dev/static/scripts/dderl.js
priv/dev/static/scripts/login.js
src/dderl_session.erl

with https://github.com/K2InformaticsGmbH/dderl/pull/465 port is no more required.

Removed port as its not used anymore

---

src/dderl_access_logger.erl
src/dderl_dal.erl
src/dderl_session.erl

is_proxy field in access log 

---

src/oci_adapter.erl

closing oci port on login error

---

src/dderl_resource.erl

Delete cookies on logout 

---

priv/dev/static/scripts/connect.js

not creating multiple connnections on multiple clicks 

---

priv/dev/static/index.js
priv/dev/static/scripts/dderl.sql.js
priv/dev/static/scripts/dderl.table.js
priv/dev/static/styles/dderl.css
priv/dev/static/styles/dderl.sql.css

Monaco editor

---

.gitignore
post_release.ps1
post_release.sh
priv/dev/package.json
priv/dev/static/index.html
priv/dev/webpack.config.js
priv/package.json
priv/swagger/package.json
src/dderl.erl

- dderl front end build into the public/dest folder
- font-awesome config removed from webpack
- wrapper build script for easy release

front-ends build paths and hierarchical yarn commands

---

src/dderl_resource.erl

local ip and port from cowboy-2.4 request

---

src/oci_adapter.erl

dderl patch oci bindless query badmatch

---

rebar.config
src/dderl_request.hrl
src/dderl_saml_handler.erl

fixes #535 
associated to https://github.com/k2informaticsgmbh/esaml/pull/7

Esaml issue

---

config/sys.config

variable required for building other applications using dderl

added lager_handler as a build variable config

---

post_release.ps1
post_release.sh

post_release script should not fail on public folder but on public/dist folder

checking public/dist instead fo public folder

---

config/service.script

using `/etc/init.d/functions` daemon function to start service

Service script update

---

docs/DDERL-CHANGELOG.md
post_release.ps1
post_release.sh
priv/dev/static/scripts/connect.js
priv/dev/static/scripts/dderl.js
priv/dev/static/scripts/login.js
rebar.config
src/dderl.app.src
src/dderl_resource.erl
src/dderl_session.erl

fixes #595
fixes #596
New version to app and Change log

release script and cookie changes

---

src/dderl_saml_handler.erl

saml url handling all methods 

---

priv/dev/static/scripts/connect.js
src/dderl.hrl
src/dderl_session.erl

Implemented background color per connection.

---

src/dderl.erl

fixes #615 
```erlang
(dderl1@127.0.0.1)6> 2019-08-20 09:51:27.716 [error] [dderl<0.1419.0>@dderl:init:110]
unable to read _build/default/lib/dderl/priv/public/dist/index.html : enoent
```

if front-end isn't build an error is shown

---

src/dderl_metrics.erl
src/dderl_sup.erl

- `dderl_metrics` module added 
- `session_count` metric added. This can be used to find the number of user sessions

added dderl_metrics and session_count metric

---

src/gen_adapter.erl

fixes PL/SQL broken parameter parsing

---

src/dderl_data_receiver.erl

fix aggregation send/receive

---

src/dderl_data_receiver.erl
src/dderl_fsm.erl

fix delete crash on tail/passthrough

---

priv/dev/static/scripts/dderl.table.js
priv/dev/static/styles/dderl.css
src/dderl_data_sender.erl
src/dderl_fsm.erl

fixes #632 
- when a filter is changed on the sender the sender process is terminated
- random id for progress bar to show the status on the correct dialog
- getting the data_info from correct ets to show the stats correctly 
with help from @acautin

Send receive fix

---

config/sys.config
config/vm.args

epmd ports are moved to vm args
fixes https://github.com/K2InformaticsGmbH/cpro/issues/40

moved epmd ports to vm args
